# Generated by Django 5.1.2 on 2024-11-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsaioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_ensaios/')),
                ('escolhida', models.BooleanField(default=False)),
                ('ensaio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='fotografo.ensaio')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_ensaios', to='fotografo.fotografo')),
            ],
        ),
    ]
