# Generated by Django 5.1.2 on 2024-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotografo', '0002_ensaiofoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensaiofoto',
            name='foto',
            field=models.BinaryField(),
        ),
    ]
